# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name': 'Comments Tutorial Comment',
                'verbose_name_plural': 'comments',
            },
        ),
    ]
