# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='playbook_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
